# Generated by Django 5.2.17 on 2026-10-05 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('growth', models.FloatField(default=1.0, help_text='Np. 1,3 = wolumeny +30 % (więcej przyjazdów).', verbose_name='Mnożnik wzrostu')),
                ('seed', models.PositiveIntegerField(default=42, verbose_name='Ziarno losowania')),
                ('shift_h', models.FloatField(default=8.0, verbose_name='Długość zmiany [h]')),
                ('container_cartons_per_h', models.FloatField(default=500, verbose_name='Rozładunek kontenera: kartonów/h na osobę')),
                ('container_people', models.PositiveSmallIntegerField(default=2, verbose_name='Osób przy kontenerze')),
                ('cartons_per_pallet', models.FloatField(default=40, verbose_name='Średnio kartonów na paletę (z kontenera)')),
                ('truck_min_per_pallet', models.FloatField(default=1.5, verbose_name='Rozładunek auta: min na paletę')),
                ('palletize_cartons_per_h', models.FloatField(default=360, verbose_name='Paletyzacja ręczna: kartonów/h na osobę')),
                ('repack_min_per_pallet', models.FloatField(default=15, verbose_name='Przepakowanie palety mieszanej: min')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scenariusz',
                'verbose_name_plural': 'Scenariusze',
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('typical', 'Dzień typowy'), ('peak', 'Dzień szczytowy')], max_length=8)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='scenario.scenario')),
            ],
            options={
                'ordering': ['scenario', '-kind'],
            },
        ),
        migrations.CreateModel(
            name='InboundStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('container40', "Kontener 40' luzem"), ('truck33', 'Auto 33-paletowe'), ('solo', 'Solówka / bus')], max_length=12, verbose_name='Typ dostawy')),
                ('arrivals_min', models.FloatField(default=0, verbose_name='Przyjazdów min')),
                ('arrivals_avg', models.FloatField(default=0, verbose_name='Przyjazdów śr.')),
                ('arrivals_max', models.FloatField(default=0, verbose_name='Przyjazdów max')),
                ('pallets_min', models.FloatField(default=0, verbose_name='Palet na przyjazd min')),
                ('pallets_avg', models.FloatField(default=0, verbose_name='Palet na przyjazd śr.')),
                ('pallets_max', models.FloatField(default=0, verbose_name='Palet na przyjazd max')),
                ('window_from', models.FloatField(default=6, verbose_name='Okno awizacji od [h]')),
                ('window_to', models.FloatField(default=14, verbose_name='Okno awizacji do [h]')),
                ('mono_pct', models.FloatField(default=100, verbose_name='% palet mono-SKU')),
                ('inspect_pct', models.FloatField(default=10, verbose_name='% palet do kontroli')),
                ('inspect_min', models.FloatField(default=2, verbose_name='Kontrola: min na paletę')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound', to='scenario.scenarioday')),
            ],
            options={
                'verbose_name': 'Strumień przyjęć',
                'verbose_name_plural': 'Strumienie przyjęć',
                'ordering': ['day', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='scenarioday',
            constraint=models.UniqueConstraint(fields=('scenario', 'kind'), name='scenario_day_unique'),
        ),
    ]
