# Generated by Django 5.2.17 on 2026-10-05 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='courier_dock_min',
            field=models.FloatField(default=30, verbose_name='Odbiór kuriera: min przy doku'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='label_min_per_parcel',
            field=models.FloatField(default=0.3, verbose_name='Etykieta i nadanie: min na paczkę'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='load_min_per_pallet',
            field=models.FloatField(default=1.5, verbose_name='Załadunek: min na paletę'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='pack_min_per_line',
            field=models.FloatField(default=0.3, verbose_name='Pakowanie: min na linię'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='pack_min_per_parcel',
            field=models.FloatField(default=1.5, verbose_name='Pakowanie: min na paczkę'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='pick_lines_per_h',
            field=models.FloatField(default=60, verbose_name='Kompletacja: linii/h na osobę'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='return_min',
            field=models.FloatField(default=6, verbose_name='Obsługa zwrotu: min'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='return_restock_pct',
            field=models.FloatField(default=70, verbose_name='Zwroty: % powrotu na skład'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='work_days',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Dni pracy w tygodniu'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='wrap_min_per_pallet',
            field=models.FloatField(default=2, verbose_name='Owijanie palety kompletowanej: min'),
        ),
        migrations.AddField(
            model_name='scenarioday',
            name='full_pallet_pct',
            field=models.FloatField(default=40, verbose_name='% palet OUT pełnych (bez kompletacji)'),
        ),
        migrations.AddField(
            model_name='scenarioday',
            name='lines_avg',
            field=models.FloatField(default=0, verbose_name='Linii na zamówienie śr.'),
        ),
        migrations.AddField(
            model_name='scenarioday',
            name='lines_max',
            field=models.FloatField(default=0, verbose_name='Linii na zamówienie max'),
        ),
        migrations.AddField(
            model_name='scenarioday',
            name='lines_min',
            field=models.FloatField(default=0, verbose_name='Linii na zamówienie min'),
        ),
        migrations.AddField(
            model_name='scenarioday',
            name='orders_avg',
            field=models.FloatField(default=0, verbose_name='Zamówień/dzień śr.'),
        ),
        migrations.AddField(
            model_name='scenarioday',
            name='orders_max',
            field=models.FloatField(default=0, verbose_name='Zamówień/dzień max'),
        ),
        migrations.AddField(
            model_name='scenarioday',
            name='orders_min',
            field=models.FloatField(default=0, verbose_name='Zamówień/dzień min'),
        ),
        migrations.AddField(
            model_name='scenarioday',
            name='parcels_avg',
            field=models.FloatField(default=0, verbose_name='Paczek/dzień śr.'),
        ),
        migrations.AddField(
            model_name='scenarioday',
            name='parcels_max',
            field=models.FloatField(default=0, verbose_name='Paczek/dzień max'),
        ),
        migrations.AddField(
            model_name='scenarioday',
            name='parcels_min',
            field=models.FloatField(default=0, verbose_name='Paczek/dzień min'),
        ),
        migrations.AddField(
            model_name='scenarioday',
            name='returns_avg',
            field=models.FloatField(default=0, verbose_name='Zwrotów/dzień śr.'),
        ),
        migrations.AddField(
            model_name='scenarioday',
            name='returns_max',
            field=models.FloatField(default=0, verbose_name='Zwrotów/dzień max'),
        ),
        migrations.AddField(
            model_name='scenarioday',
            name='returns_min',
            field=models.FloatField(default=0, verbose_name='Zwrotów/dzień min'),
        ),
        migrations.AlterField(
            model_name='inboundstream',
            name='kind',
            field=models.CharField(choices=[('container40', "Kontener 40' luzem"), ('truck33', 'Auto 33-paletowe'), ('solo', 'Solówka / bus'), ('crossdock', 'Cross-dock (auto)')], max_length=12, verbose_name='Typ dostawy'),
        ),
        migrations.AlterField(
            model_name='inboundstream',
            name='window_from',
            field=models.FloatField(default=6, verbose_name='Okno awizacji od'),
        ),
        migrations.AlterField(
            model_name='inboundstream',
            name='window_to',
            field=models.FloatField(default=14, verbose_name='Okno awizacji do'),
        ),
        migrations.CreateModel(
            name='OutboundStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('truck33', 'Auto 33-paletowe'), ('solo', 'Solówka / bus'), ('courier', 'Kurier (odbiór paczek)'), ('crossdock', 'Cross-dock (auto)')], max_length=12, verbose_name='Typ auta')),
                ('departures_min', models.FloatField(default=0, verbose_name='Wyjazdów min')),
                ('departures_avg', models.FloatField(default=0, verbose_name='Wyjazdów śr.')),
                ('departures_max', models.FloatField(default=0, verbose_name='Wyjazdów max')),
                ('pallets_min', models.FloatField(default=0, verbose_name='Palet na auto min')),
                ('pallets_avg', models.FloatField(default=0, verbose_name='Palet na auto śr.')),
                ('pallets_max', models.FloatField(default=0, verbose_name='Palet na auto max')),
                ('window_from', models.FloatField(default=12, verbose_name='Załadunek od')),
                ('window_to', models.FloatField(default=20, verbose_name='Cut-off')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound', to='scenario.scenarioday')),
            ],
            options={
                'verbose_name': 'Strumień wydań',
                'verbose_name_plural': 'Strumienie wydań',
                'ordering': ['day', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(choices=[('unload', 'Rozładunek'), ('palletize', 'Paletyzacja i przepakowanie'), ('inspect', 'Kontrola'), ('pick', 'Kompletacja'), ('pack', 'Pakowanie i nadanie'), ('load', 'Załadunek i owijanie'), ('returns', 'Zwroty')], max_length=10, verbose_name='Proces')),
                ('start_h', models.FloatField(default=6, verbose_name='Od')),
                ('end_h', models.FloatField(default=14, verbose_name='Do')),
                ('break_min', models.FloatField(default=30, verbose_name='Przerwa [min]')),
                ('people', models.PositiveSmallIntegerField(default=1, verbose_name='Osób')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='scenario.scenario')),
            ],
            options={
                'verbose_name': 'Zmiana',
                'verbose_name_plural': 'Zmiany',
                'ordering': ['scenario', 'process', 'start_h', 'pk'],
            },
        ),
    ]
