# Generated by Django 5.2.17 on 2026-10-05 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0002_wydania_obsada'),
        ('twin', '0003_konstrukcja_hali'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='battery_h',
            field=models.FloatField(default=6, verbose_name='Flota: praca na baterii [h]'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='charge_h',
            field=models.FloatField(default=1.5, verbose_name='Flota: ładowanie [h]'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='fleet_min_per_move',
            field=models.FloatField(default=4, verbose_name='Flota: min na ruch palety (z dojazdem)'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='fleet_units',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Flota: wózków / AGV'),
        ),
        migrations.CreateModel(
            name='ScenarioRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_kind', models.CharField(choices=[('typical', 'Dzień typowy'), ('peak', 'Dzień szczytowy')], max_length=8)),
                ('runs', models.PositiveSmallIntegerField(default=12)),
                ('seed', models.PositiveIntegerField(default=42)),
                ('duration_s', models.FloatField(default=0)),
                ('result', models.JSONField(default=dict)),
                ('events', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_runs', to='twin.warehousemodel')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='scenario.scenario')),
            ],
            options={
                'verbose_name': 'Symulacja scenariusza',
                'verbose_name_plural': 'Symulacje scenariuszy',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
