# Generated by Django 5.2.17 on 2026-10-05 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_klasy_systemowe'),
        ('scenario', '0003_symulacja_dnia'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='fleet_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='equipment.equipment', verbose_name='Flota: sprzęt z katalogu'),
        ),
    ]
