# Generated by Django 5.2.17 on 2026-10-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0004_flota_z_katalogu'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='peak_days_year',
            field=models.PositiveSmallIntegerField(default=30, help_text='Koszty roczne: tyle dni liczonych jak dzień szczytowy, reszta dni pracy jak typowy.', verbose_name='Dni szczytowe w roku'),
        ),
    ]
