# Generated by Django 5.2.17 on 2026-10-05 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0005_dni_szczytowe'),
        ('twin', '0006_sprzet_z_katalogu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('slides', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcases', to='twin.warehousemodel', verbose_name='Model hali')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcases', to='scenario.scenariorun', verbose_name='Wynik symulacji')),
            ],
            options={
                'verbose_name': 'Prezentacja 3D',
                'verbose_name_plural': 'Prezentacje 3D',
                'ordering': ['-updated_at', '-pk'],
            },
        ),
    ]
