# Generated by Django 5.2.17 on 2026-10-05 19:14

from django.db import migrations, models


def fill(apps, schema_editor):
    Run = apps.get_model("scenario", "ScenarioRun")
    Run.objects.exclude(events=[]).update(has_events=True)

class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0007_dni_scenariuszy'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariorun',
            name='has_events',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(fill, migrations.RunPython.noop),
    ]
