# Generated by Django 5.2.17 on 2026-10-06 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_klasy_rynkowe'),
        ('scenario', '0008_przebieg_ma_zdarzenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveSmallIntegerField(default=1, verbose_name='Sztuk')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_fleets', to='equipment.equipment', verbose_name='Sprzęt z katalogu')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet', to='scenario.scenario')),
            ],
            options={
                'verbose_name': 'Grupa floty',
                'verbose_name_plural': 'Flota mieszana',
                'ordering': ['scenario', 'pk'],
            },
        ),
    ]
