# Generated by Django 5.2.17 on 2026-10-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario', '0009_flota_mieszana'),
    ]

    operations = [
        migrations.AddField(
            model_name='showcase',
            name='share_expires',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='showcase',
            name='share_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
