# Generated by Django 5.2.17 on 2026-10-05 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pallet_truck', 'Wózek paletowy elektryczny'), ('counterbalance', 'Wózek czołowy'), ('reach', 'Reach truck (wysokiego składowania)'), ('vna', 'VNA / wózek systemowy (kombi)'), ('agv', 'AGV paletowy'), ('amr', 'AMR'), ('conveyor', 'Przenośnik'), ('sorter', 'Sorter')], max_length=16, verbose_name='Typ')),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa')),
                ('is_system', models.BooleanField(default=False, editable=False, verbose_name='Klasa systemowa')),
                ('speed_loaded_kmh', models.FloatField(verbose_name='Jazda z ładunkiem [km/h]')),
                ('speed_empty_kmh', models.FloatField(verbose_name='Jazda bez ładunku [km/h]')),
                ('lift_speed_ms', models.FloatField(blank=True, null=True, verbose_name='Podnoszenie [m/s]')),
                ('lower_speed_ms', models.FloatField(blank=True, null=True, verbose_name='Opuszczanie [m/s]')),
                ('max_lift_m', models.FloatField(blank=True, null=True, verbose_name='Maks. wysokość podnoszenia [m]')),
                ('capacity_kg', models.PositiveIntegerField(verbose_name='Udźwig nominalny [kg]')),
                ('lift_curve', models.JSONField(blank=True, default=list, help_text='Punkty [wysokość m, udźwig kg], np. [[6, 1600], [10, 1000]].', verbose_name='Redukcja udźwigu')),
                ('aisle_m', models.FloatField(blank=True, null=True, verbose_name='Wymagana alejka robocza Ast [m]')),
                ('pick_s', models.FloatField(blank=True, null=True, verbose_name='Pobranie palety [s]')),
                ('drop_s', models.FloatField(blank=True, null=True, verbose_name='Odłożenie palety [s]')),
                ('battery_h', models.FloatField(blank=True, null=True, verbose_name='Praca na baterii [h]')),
                ('charge_h', models.FloatField(blank=True, null=True, verbose_name='Ładowanie / wymiana [h]')),
                ('turn_radius_m', models.FloatField(blank=True, null=True, verbose_name='Promień skrętu [m]')),
                ('length_m', models.FloatField(blank=True, null=True, verbose_name='Długość [m]')),
                ('width_m', models.FloatField(blank=True, null=True, verbose_name='Szerokość [m]')),
                ('throughput_h', models.PositiveIntegerField(blank=True, null=True, verbose_name='Wydajność nominalna [szt./h]')),
                ('cost_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Koszt zakupu [zł]')),
                ('cost_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Koszt godziny pracy [zł]')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sprzęt',
                'verbose_name_plural': 'Katalog sprzętu',
                'ordering': ['kind', '-is_system', 'name'],
            },
        ),
    ]
