# Generated by Django 5.2.17 on 2026-10-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_klasy_systemowe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(editable=False, max_length=24, unique=True)),
                ('label', models.CharField(editable=False, max_length=120)),
                ('unit', models.CharField(editable=False, max_length=24)),
                ('low', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Od')),
                ('high', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Do')),
                ('order', models.PositiveSmallIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Stawka kosztowa',
                'verbose_name_plural': 'Stawki kosztowe',
                'ordering': ['order', 'key'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='cost_per_hour_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Godzina pracy do [zł]'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='cost_purchase_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Zakup do [zł]'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cost_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Godzina pracy od [zł]'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cost_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Zakup od [zł]'),
        ),
    ]
