# Generated by Django 5.2.17 on 2026-10-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_stawki_domyslne'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='Kody osprzętu — zmniejszają udźwig i wydłużają obsługę palety.', verbose_name='Osprzęt'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Producent'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='kind',
            field=models.CharField(choices=[('pallet_truck', 'Wózek paletowy elektryczny'), ('counterbalance', 'Wózek czołowy'), ('reach', 'Reach truck (wysokiego składowania)'), ('vna', 'VNA / wózek systemowy (kombi)'), ('agv', 'AGV paletowy'), ('amr', 'AMR'), ('stacker', 'Wózek podnośnikowy (unoszący z masztem)'), ('order_picker', 'Wózek do kompletacji'), ('tractor', 'Ciągnik'), ('conveyor', 'Przenośnik'), ('sorter', 'Sorter')], max_length=16, verbose_name='Typ'),
        ),
    ]
