# Generated by Django 5.2.17 on 2026-10-05 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł filmu')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('approved', 'Tekst zatwierdzony'), ('audio', 'Lektor'), ('render', 'Render ujęć'), ('montage', 'Montaż'), ('done', 'Gotowe')], db_index=True, default='draft', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='twin.warehousemodel', verbose_name='Model hali')),
            ],
            options={
                'verbose_name': 'Prezentacja',
                'verbose_name_plural': 'Prezentacje',
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Kolejność')),
                ('preset', models.CharField(choices=[('przelot', 'Przelot nad halą'), ('orbita', 'Orbita wokół hali'), ('przejazd', 'Przejazd wzdłuż hali (nisko)'), ('plan', 'Plan z góry'), ('ogolny', 'Widok ogólny (statyczny)')], default='ogolny', max_length=12, verbose_name='Ujęcie')),
                ('text', models.TextField(verbose_name='Kwestia lektora')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='studio.presentation')),
            ],
            options={
                'verbose_name': 'Ujęcie prezentacji',
                'verbose_name_plural': 'Ujęcia prezentacji',
                'ordering': ['order', 'pk'],
            },
        ),
    ]
