# Generated by Django 5.2.17 on 2026-10-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('voice_id', models.CharField(max_length=64)),
                ('model_id', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('audio', models.FileField(upload_to='voice/%Y/%m/')),
                ('duration_s', models.FloatField()),
                ('alignment', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nagranie lektora',
                'verbose_name_plural': 'Nagrania lektora',
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='voice_id',
            field=models.CharField(blank=True, default='', help_text='Puste = domyślny głos z ELEVENLABS_VOICE_ID.', max_length=64, verbose_name='Głos lektora (voice_id)'),
        ),
        migrations.AddField(
            model_name='shot',
            name='voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to='studio.voicetrack'),
        ),
    ]
