# Generated by Django 5.2.17 on 2026-10-05 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
        ('studio', '0002_lektor'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='render',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_shots', to='render.renderjob'),
        ),
        migrations.AddField(
            model_name='shot',
            name='render_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='MontageJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_key', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'W kolejce'), ('running', 'Renderuje się'), ('done', 'Gotowe'), ('error', 'Błąd')], db_index=True, default='queued', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('worker', models.CharField(blank=True, default='', max_length=80)),
                ('claim_token', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('result', models.FileField(blank=True, upload_to='films/%Y/%m/')),
                ('log', models.TextField(blank=True, default='')),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='montages', to='studio.presentation')),
            ],
            options={
                'verbose_name': 'Montaż filmu',
                'verbose_name_plural': 'Montaże filmów',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
