# Generated by Django 5.2.17 on 2026-10-05 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
        ('studio', '0003_render_montaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='still',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studio_stills', to='render.renderjob'),
        ),
        migrations.AddField(
            model_name='shot',
            name='still_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
