# Generated by Django 5.2.17 on 2026-10-05 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Kod materiału')),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nazwa')),
                ('group', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Grupa towarowa')),
                ('unit', models.CharField(blank=True, default='SZT', max_length=10, verbose_name='Jednostka bazowa')),
                ('pcs_per_carton', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sztuk w kartonie')),
                ('carton_l_cm', models.FloatField(blank=True, null=True, verbose_name='Karton dł. [cm]')),
                ('carton_w_cm', models.FloatField(blank=True, null=True, verbose_name='Karton szer. [cm]')),
                ('carton_h_cm', models.FloatField(blank=True, null=True, verbose_name='Karton wys. [cm]')),
                ('carton_kg', models.FloatField(blank=True, null=True, verbose_name='Karton waga [kg]')),
                ('cartons_per_pallet', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kartonów na palecie')),
                ('pallet_h_cm', models.FloatField(blank=True, null=True, verbose_name='Wys. palety z towarem [cm]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Materiał',
                'verbose_name_plural': 'Materiały',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('materials', 'Materiały'), ('locations', 'Master lokalizacji'), ('stock', 'Stany')], max_length=12, verbose_name='Rodzaj')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa / plik')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_ok', models.PositiveIntegerField(default=0)),
                ('rows_rejected', models.PositiveIntegerField(default=0)),
                ('rejects', models.JSONField(blank=True, default=list, verbose_name='Odrzucone (próbka)')),
                ('columns', models.JSONField(blank=True, default=dict, verbose_name='Rozpoznane kolumny')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import danych',
                'verbose_name_plural': 'Importy danych',
                'ordering': ['-uploaded_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(db_index=True, max_length=50, verbose_name='Lokalizacja')),
                ('material_code', models.CharField(max_length=40, verbose_name='Materiał')),
                ('qty', models.FloatField(default=0, verbose_name='Ilość')),
                ('unit', models.CharField(blank=True, default='', max_length=10, verbose_name='Jednostka')),
                ('hu', models.CharField(blank=True, default='', max_length=40, verbose_name='Nośnik / HU')),
                ('lot', models.CharField(blank=True, default='', max_length=40, verbose_name='Partia')),
                ('expiry', models.DateField(blank=True, null=True, verbose_name='Data ważności')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='masterdata.importlog')),
            ],
            options={
                'verbose_name': 'Pozycja stanu',
                'verbose_name_plural': 'Stany',
                'ordering': ['location_code', 'pk'],
            },
        ),
    ]
