# Generated by Django 5.2.17 on 2026-10-05 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nazwa')),
                ('length_cm', models.FloatField(verbose_name='Długość [cm]')),
                ('width_cm', models.FloatField(verbose_name='Szerokość [cm]')),
                ('height_cm', models.FloatField(default=14.4, verbose_name='Wysokość własna [cm]')),
                ('weight_kg', models.FloatField(default=25, verbose_name='Waga własna [kg]')),
                ('max_load_h_cm', models.FloatField(default=180, verbose_name='Max wysokość ładunku [cm]')),
                ('max_load_kg', models.FloatField(default=1000, verbose_name='Max waga ładunku [kg]')),
                ('is_default', models.BooleanField(default=False, verbose_name='Domyślny')),
            ],
            options={
                'verbose_name': 'Nośnik',
                'verbose_name_plural': 'Nośniki',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='abc_manual',
            field=models.CharField(blank=True, choices=[('', 'z historii'), ('A', 'A'), ('B', 'B'), ('C', 'C')], default='', max_length=1, verbose_name='Klasa ABC (ręcznie)'),
        ),
        migrations.AddField(
            model_name='material',
            name='adr',
            field=models.BooleanField(default=False, verbose_name='ADR / niebezpieczny'),
        ),
        migrations.AddField(
            model_name='material',
            name='cartons_per_layer',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kartonów na warstwę'),
        ),
        migrations.AddField(
            model_name='material',
            name='high_value',
            field=models.BooleanField(default=False, verbose_name='Wysoka wartość'),
        ),
        migrations.AddField(
            model_name='material',
            name='layers_per_pallet',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Warstw na palecie'),
        ),
        migrations.AddField(
            model_name='material',
            name='oversize',
            field=models.BooleanField(default=False, verbose_name='Gabaryt / dłużyca'),
        ),
        migrations.AddField(
            model_name='material',
            name='piece_h_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Sztuka wys. [cm]'),
        ),
        migrations.AddField(
            model_name='material',
            name='piece_kg',
            field=models.FloatField(blank=True, null=True, verbose_name='Sztuka waga [kg]'),
        ),
        migrations.AddField(
            model_name='material',
            name='piece_l_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Sztuka dł. [cm]'),
        ),
        migrations.AddField(
            model_name='material',
            name='piece_w_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Sztuka szer. [cm]'),
        ),
        migrations.AddField(
            model_name='material',
            name='temp_controlled',
            field=models.BooleanField(default=False, verbose_name='Temperatura kontrolowana'),
        ),
        migrations.AddField(
            model_name='material',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.carrier', verbose_name='Nośnik'),
        ),
        migrations.CreateModel(
            name='PalletClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('height', 'Wysokość [cm]'), ('weight', 'Waga [kg]')], max_length=6, verbose_name='Rodzaj')),
                ('label', models.CharField(max_length=30, verbose_name='Nazwa klasy')),
                ('limit', models.FloatField(verbose_name='Do (włącznie)')),
            ],
            options={
                'verbose_name': 'Klasa palety',
                'verbose_name_plural': 'Klasy palet',
                'ordering': ['kind', 'limit'],
                'unique_together': {('kind', 'label')},
            },
        ),
        migrations.AddField(
            model_name='material',
            name='height_class',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'height'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masterdata.palletclass', verbose_name='Klasa wysokości'),
        ),
        migrations.AddField(
            model_name='material',
            name='weight_class',
            field=models.ForeignKey(blank=True, limit_choices_to={'kind': 'weight'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='masterdata.palletclass', verbose_name='Klasa wagi'),
        ),
    ]
