# Generated by Django 5.2.17 on 2026-10-05 08:58

import django.db.models.deletion
import twin.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('beam_mm', models.IntegerField(default=2700, verbose_name='Szerokość belki [mm]')),
                ('pallets_per_beam', models.PositiveSmallIntegerField(default=3, verbose_name='Palet na belce')),
                ('depth_mm', models.IntegerField(default=1100, verbose_name='Głębokość [mm]')),
                ('levels', models.JSONField(blank=True, default=list, verbose_name='Poziomy (od dołu)')),
                ('notes', models.CharField(blank=True, default='', max_length=200, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Szablon gniazda',
                'verbose_name_plural': 'Szablony gniazd',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocationMasterBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('location_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa modelu')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_width_m', models.FloatField(default=50, verbose_name='Szerokość hali [m]')),
                ('floor_depth_m', models.FloatField(default=30, verbose_name='Głębokość hali [m]')),
            ],
            options={
                'verbose_name': 'Model magazynu',
                'verbose_name_plural': 'Modele magazynów',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseRackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod typu')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('kind', models.CharField(choices=[('rack', 'Regał'), ('zone', 'Strefa')], default='rack', max_length=8, verbose_name='Rodzaj')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='Opis (znaczenie kodu)')),
                ('width_mm', models.IntegerField(default=800, verbose_name='Szer. fiz. miejsca [mm]')),
                ('manip_mm', models.IntegerField(default=900, verbose_name='Szer. z manipulacją [mm]')),
                ('depth_mm', models.IntegerField(default=1100, verbose_name='Głębokość [mm]')),
                ('max_weight_kg', models.FloatField(default=1200, verbose_name='Max waga [kg]')),
                ('max_volume_m3', models.FloatField(default=2.5, verbose_name='Max objętość [m³]')),
                ('level_heights', models.JSONField(default=dict, verbose_name='Wysokości poziomów [mm]')),
                ('level_cols', models.JSONField(default=dict, help_text='np. {"1":1,"2":2,"3":1} — ile kolumn na każdym poziomie. Puste = 1 wszędzie.', verbose_name='Kolumny per poziom')),
                ('level_weights', models.JSONField(default=dict, help_text='np. {"1":1000,"2":300} — max waga na poziom (etykiety kg w widoku 3D).', verbose_name='Nośność poziomów [kg]')),
                ('color_hex', models.CharField(default='#f59e0b', max_length=7, verbose_name='Kolor 3D')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Typ regału (3D)',
                'verbose_name_plural': 'Typy regałów (3D)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseHallFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('dock', 'Dok przeładunkowy'), ('gate', 'Brama'), ('corridor', 'Korytarz / ciąg komunikacyjny'), ('block_zone', 'Strefa blokowa / nietypowa'), ('returns', 'Strefa zwrotów'), ('leader', 'Stanowisko lidera'), ('station', 'Stanowisko / punkt kontroli'), ('other', 'Inny obszar')], default='other', max_length=20, verbose_name='Typ elementu')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Etykieta')),
                ('zone_code', models.CharField(blank=True, help_text='Dla stref blokowych/zwrotów — łapie kody po prefiksie', max_length=20, verbose_name='Prefiks kodów lokalizacji')),
                ('x_m', models.FloatField(default=0, verbose_name='Pozycja X [m]')),
                ('y_m', models.FloatField(default=0, verbose_name='Pozycja Y [m]')),
                ('width_m', models.FloatField(default=2, verbose_name='Szerokość [m]')),
                ('depth_m', models.FloatField(default=2, verbose_name='Głębokość [m]')),
                ('angle_deg', models.FloatField(default=0, verbose_name='Kąt obrotu [°]')),
                ('color_hex', models.CharField(blank=True, max_length=7, verbose_name='Kolor')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Uwagi')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='twin.warehousemodel')),
            ],
            options={
                'verbose_name': 'Element hali',
                'verbose_name_plural': 'Elementy hali',
                'ordering': ['kind', 'label'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseDesignVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa wariantu')),
                ('source', models.CharField(choices=[('blender', 'Blender (zestaw projektowy)'), ('model', 'Model magazynu')], default='blender', max_length=10, verbose_name='Źródło')),
                ('floor_width_m', models.FloatField(default=50, verbose_name='Szerokość hali [m]')),
                ('floor_depth_m', models.FloatField(default=30, verbose_name='Głębokość hali [m]')),
                ('elements', models.JSONField(default=list, verbose_name='Elementy')),
                ('features', models.JSONField(default=list, verbose_name='Elementy hali (doki, strefy)')),
                ('kpi', models.JSONField(default=dict, verbose_name='Wskaźniki')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_variants', to='twin.warehousemodel', verbose_name='Model bazowy')),
            ],
            options={
                'verbose_name': 'Wariant projektu magazynu',
                'verbose_name_plural': 'Warianty projektu magazynu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseModelRack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(db_index=True, max_length=20, verbose_name='Strefa')),
                ('rack_id', models.CharField(max_length=20, verbose_name='Nr regału')),
                ('n_bays', models.IntegerField(default=1, verbose_name='Liczba boków (bays)')),
                ('n_levels', models.IntegerField(default=3, verbose_name='Liczba poziomów')),
                ('bay_width_cm', models.IntegerField(default=100, verbose_name='Szerokość boku [cm]')),
                ('depth_cm', models.IntegerField(default=80, verbose_name='Głębokość regału [cm]')),
                ('level_height_cm', models.IntegerField(default=200, verbose_name='Wys. poziomów [cm]')),
                ('x_m', models.FloatField(blank=True, null=True, verbose_name='Pozycja X [m]')),
                ('y_m', models.FloatField(blank=True, null=True, verbose_name='Pozycja Y [m]')),
                ('angle_deg', models.FloatField(default=0, verbose_name='Kąt obrotu [°]')),
                ('bay_numbers', models.CharField(blank=True, default='', help_text='Zakresy, np. 10-47,50. Puste = 1…liczba gniazd.', max_length=200, validators=[twin.models.validate_bay_numbers], verbose_name='Numeracja gniazd')),
                ('reverse', models.BooleanField(default=False, verbose_name='Numeracja od końca rzędu')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='twin.warehousemodel')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='twin.baytemplate', verbose_name='Szablon gniazda')),
            ],
            options={
                'verbose_name': 'Regał modelu',
                'verbose_name_plural': 'Regały modelu',
                'ordering': ['zone', 'rack_id'],
                'unique_together': {('model', 'zone', 'rack_id')},
            },
        ),
        migrations.CreateModel(
            name='WarehouseTaskBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa importu')),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Plik')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('queued', 'W kolejce'), ('running', 'Import trwa'), ('done', 'Zaimportowano'), ('error', 'Błąd')], default='queued', max_length=10)),
                ('message', models.TextField(blank=True, default='', verbose_name='Komunikat')),
                ('tz', models.CharField(choices=[('Europe/Warsaw', 'Czas lokalny (Europe/Warsaw)'), ('UTC', 'UTC')], default='Europe/Warsaw', max_length=40, verbose_name='Strefa czasowa pliku')),
                ('kind_map', models.JSONField(blank=True, default=dict, verbose_name='Nadpisania mapowania (proces → rodzaj)')),
                ('row_count', models.IntegerField(default=0, verbose_name='Zadań')),
                ('error_count', models.IntegerField(default=0, verbose_name='Błędnych wierszy')),
                ('first_confirmed', models.DateTimeField(blank=True, null=True)),
                ('last_confirmed', models.DateTimeField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict, verbose_name='Statystyki')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import zadań magazynowych EWM',
                'verbose_name_plural': 'Importy zadań magazynowych EWM',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.CharField(db_index=True, max_length=50)),
                ('level', models.IntegerField(default=1)),
                ('warehouse_type', models.CharField(blank=True, default='', max_length=50)),
                ('height_mm', models.IntegerField(default=0)),
                ('width_mm', models.IntegerField(default=0)),
                ('depth_mm', models.IntegerField(default=0)),
                ('max_volume_m3', models.FloatField(default=0.0)),
                ('max_weight_kg', models.FloatField(default=0.0)),
                ('blocked_pick', models.BooleanField(default=False, verbose_name='Blokada wydania')),
                ('blocked_put', models.BooleanField(default=False, verbose_name='Blokada umieszczania')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='twin.warehouselocationmasterbatch')),
            ],
            options={
                'ordering': ['location_code', 'id'],
                'unique_together': {('batch', 'location_code')},
            },
        ),
        migrations.CreateModel(
            name='LocationOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bay', models.IntegerField(verbose_name='Gniazdo (numer z adresu)')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Pozycja palety')),
                ('letter', models.CharField(blank=True, default='', max_length=1, verbose_name='Litera poziomu')),
                ('half', models.PositiveSmallIntegerField(default=0, verbose_name='Połówka (0/1/2)')),
                ('action', models.CharField(choices=[('template', 'Inny szablon gniazda'), ('skip', 'Pomiń'), ('add', 'Dodaj miejsce'), ('rename', 'Własny adres'), ('ewm_type', 'Inny typ EWM'), ('split', 'Podziel na połówki'), ('unsplit', 'Scal połówki'), ('block', 'Blokada')], max_length=10, verbose_name='Wyjątek')),
                ('value', models.CharField(blank=True, default='', max_length=50, verbose_name='Wartość (kod / typ EWM)')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bay_overrides', to='twin.baytemplate', verbose_name='Szablon (dla wyjątku gniazda)')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='twin.warehousemodelrack')),
            ],
            options={
                'verbose_name': 'Wyjątek adresu',
                'verbose_name_plural': 'Wyjątki adresów',
                'ordering': ['rack', 'bay', 'letter', 'position', 'half'],
                'constraints': [models.UniqueConstraint(fields=('rack', 'bay', 'position', 'letter', 'half', 'action'), name='locationoverride_unique')],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(blank=True, default='', max_length=20, verbose_name='Nr WT')),
                ('process_type', models.CharField(blank=True, default='', max_length=10, verbose_name='Rodzaj procesu mag.')),
                ('kind', models.CharField(choices=[('putaway', 'Przyjęcie / odłożenie'), ('replenishment', 'Uzupełnienie'), ('picking', 'Kompletacja'), ('outbound', 'Wydanie / załadunek'), ('move', 'Przesunięcie')], default='move', max_length=14, verbose_name='Rodzaj ruchu')),
                ('src_location', models.CharField(blank=True, default='', max_length=50, verbose_name='Lokalizacja źródłowa')),
                ('dst_location', models.CharField(blank=True, default='', max_length=50, verbose_name='Lokalizacja docelowa')),
                ('material', models.CharField(blank=True, default='', max_length=50, verbose_name='Materiał')),
                ('lot', models.CharField(blank=True, default='', max_length=32, verbose_name='Partia')),
                ('qty', models.FloatField(blank=True, null=True, verbose_name='Ilość')),
                ('unit', models.CharField(blank=True, default='', max_length=10, verbose_name='JM')),
                ('src_hu', models.CharField(blank=True, default='', max_length=40, verbose_name='HU źródłowa')),
                ('dst_hu', models.CharField(blank=True, default='', max_length=40, verbose_name='HU docelowa')),
                ('document', models.CharField(blank=True, default='', max_length=35, verbose_name='Dokument')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Utworzono')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Potwierdzono')),
                ('user', models.CharField(blank=True, default='', max_length=40, verbose_name='Użytkownik')),
                ('resource', models.CharField(blank=True, default='', max_length=40, verbose_name='Zasób')),
                ('queue', models.CharField(blank=True, default='', max_length=40, verbose_name='Kolejka')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='twin.warehousetaskbatch')),
            ],
            options={
                'verbose_name': 'Zadanie magazynowe EWM',
                'verbose_name_plural': 'Zadania magazynowe EWM',
                'indexes': [models.Index(fields=['batch', 'confirmed_at'], name='twin_wareho_batch_i_89b9d4_idx'), models.Index(fields=['batch', 'src_location'], name='twin_wareho_batch_i_9551c3_idx'), models.Index(fields=['batch', 'dst_location'], name='twin_wareho_batch_i_9fd31a_idx')],
            },
        ),
    ]
