# Generated by Django 5.2.17 on 2026-10-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousehallfeature',
            name='kind',
            field=models.CharField(choices=[('dock', 'Dok przeładunkowy'), ('gate', 'Brama'), ('corridor', 'Korytarz / ciąg komunikacyjny'), ('block_zone', 'Strefa blokowa / nietypowa'), ('staging', 'Pole odkładcze'), ('returns', 'Strefa zwrotów'), ('leader', 'Stanowisko lidera'), ('station', 'Stanowisko / punkt kontroli'), ('other', 'Inny obszar')], default='other', max_length=20, verbose_name='Typ elementu'),
        ),
    ]
