# Generated by Django 5.2.17 on 2026-10-05 12:50

from django.db import migrations, models


def shelves(apps, schema_editor):
    """Istniejące regały półkowe (poziom < 1 m, jak blender_scene.SHELF_LEVEL_M) → alejka półek, nie reach."""
    apps.get_model("twin", "WarehouseModelRack").objects.filter(level_height_cm__lt=100).update(equipment="shelf")


class Migration(migrations.Migration):

    dependencies = [
        ('twin', '0002_pole_odkladcze'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousemodel',
            name='clear_height_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Wysokość w świetle [m]'),
        ),
        migrations.AddField(
            model_name='warehousemodel',
            name='columns',
            field=models.JSONField(blank=True, default=dict, verbose_name='Siatka słupów'),
        ),
        migrations.AddField(
            model_name='warehousemodel',
            name='underlay',
            field=models.FileField(blank=True, upload_to='underlays/%Y/%m/', verbose_name='Podkład (rzut hali)'),
        ),
        migrations.AddField(
            model_name='warehousemodel',
            name='underlay_meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Podkład: skala i położenie'),
        ),
        migrations.AddField(
            model_name='warehousemodelrack',
            name='equipment',
            field=models.CharField(choices=[('reach', 'Reach truck (alejka ~3,0 m)'), ('vna', 'Wózek systemowy VNA (alejka ~1,8 m)'), ('shelf', 'Półki, kompletacja z wózka EPT (alejka ~2,0 m)')], default='reach', max_length=6, verbose_name='Sprzęt obsługi (wymagana alejka)'),
        ),
        migrations.AlterField(
            model_name='warehousehallfeature',
            name='kind',
            field=models.CharField(choices=[('dock', 'Dok przeładunkowy'), ('gate', 'Brama'), ('corridor', 'Korytarz / ciąg komunikacyjny'), ('block_zone', 'Strefa blokowa / nietypowa'), ('staging', 'Pole odkładcze'), ('returns', 'Strefa zwrotów'), ('leader', 'Stanowisko lidera'), ('station', 'Stanowisko / punkt kontroli'), ('other', 'Inny obszar'), ('fire_route', 'Droga pożarowa / ewakuacyjna'), ('charging', 'Strefa ładowania (wózki / AGV)'), ('walkway', 'Droga ruchu pieszego'), ('truckway', 'Droga ruchu wózków'), ('zone_temp', 'Strefa specjalna: temperatura kontrolowana'), ('zone_adr', 'Strefa specjalna: ADR (towary niebezpieczne)'), ('zone_oversize', 'Strefa specjalna: gabaryty / dłużyca'), ('zone_value', 'Strefa specjalna: towary wysokiej wartości')], default='other', max_length=20, verbose_name='Typ elementu'),
        ),
        migrations.RunPython(shelves, migrations.RunPython.noop),
    ]
