# Generated by Django 5.2.17 on 2026-10-05 14:08

from django.db import migrations, models


def _guess(label):
    """Kopia heurystyki z etykiety (z S3a) z chwili migracji — migracje mają być zamrożone."""
    s = f" {(label or '').lower()} "
    if "wspóln" in s:
        return "shared"
    if "pacz" in s or "kurier" in s:
        return "courier"
    if "kontener" in s:
        return "in_container"
    if "przyj" in s or "paletowy" in s or " in " in s:
        return "in_pallet"
    return "out"


def fill_roles(apps, schema_editor):
    Feature = apps.get_model("twin", "WarehouseHallFeature")
    rows = list(Feature.objects.filter(kind__in=("dock", "gate"), dock_role=""))
    for f in rows:
        f.dock_role = _guess(f.label)
    Feature.objects.bulk_update(rows, ["dock_role"])


class Migration(migrations.Migration):

    dependencies = [
        ('twin', '0003_konstrukcja_hali'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousehallfeature',
            name='dock_role',
            field=models.CharField(blank=True, choices=[('in_container', 'Przyjęcia: kontenery'), ('in_pallet', 'Przyjęcia: palety (auta)'), ('out', 'Wydania'), ('courier', 'Kurier / paczki'), ('shared', 'Wspólny IN + OUT')], default='', help_text='Dla doków i bram; puste = z etykiety.', max_length=12, verbose_name='Rola doku'),
        ),
        migrations.AddField(
            model_name='warehousemodelrack',
            name='load_kg',
            field=models.PositiveIntegerField(default=1000, help_text='Na jedną paletę (para belek / pole). Ostrzeżenia rozmieszczenia (S3b).', verbose_name='Nośność miejsca paletowego [kg]'),
        ),
        migrations.RunPython(fill_roles, migrations.RunPython.noop),
    ]
