# Generated by Django 5.2.17 on 2026-10-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twin', '0004_rola_doku_nosnosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousemodel',
            name='site',
            field=models.JSONField(blank=True, default=dict, verbose_name='Działka'),
        ),
    ]
