# Generated by Django 5.2.17 on 2026-10-05 16:22

import django.db.models.deletion
from django.db import migrations, models


def assign(apps, schema_editor):
    """Dotychczasowa kategoria regału (reach/vna) → najmniejsza klasa systemowa, która sięga najwyższej belki
    (gdy żadna nie sięga — najwyższa). Półki zostają bez sprzętu (kompletacja ręczna)."""
    Rack, Equipment = apps.get_model("twin", "WarehouseModelRack"), apps.get_model("equipment", "Equipment")
    classes = {k: sorted(Equipment.objects.filter(is_system=True, kind=k), key=lambda e: e.max_lift_m or 0)
               for k in ("reach", "vna")}
    for r in Rack.objects.filter(equipment__in=("reach", "vna")).only("pk", "equipment", "n_levels", "level_height_cm"):
        cands = classes[r.equipment]
        if not cands:
            continue
        top = max(0, r.n_levels - 1) * r.level_height_cm / 100
        pick = next((e for e in cands if (e.max_lift_m or 0) >= top), cands[-1])
        Rack.objects.filter(pk=r.pk).update(equipment_model=pick)


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_klasy_systemowe'),
        ('twin', '0005_dzialka'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousemodelrack',
            name='equipment_model',
            field=models.ForeignKey(blank=True, help_text='Konkretna klasa/model: alejka, wysokość podnoszenia, udźwig (K1).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='equipment.equipment', verbose_name='Sprzęt z katalogu'),
        ),
        migrations.RunPython(assign, migrations.RunPython.noop),
    ]
