# Generated by Django 5.2.17 on 2026-10-05 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RenderJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset', models.CharField(choices=[('przelot', 'Przelot nad halą'), ('orbita', 'Orbita wokół hali'), ('przejazd', 'Przejazd wzdłuż hali (nisko)'), ('plan', 'Plan z góry'), ('ogolny', 'Widok ogólny (statyczny)')], default='przelot', max_length=12, verbose_name='Ujęcie')),
                ('kind', models.CharField(choices=[('video', 'Klip MP4'), ('still', 'Kadr PNG')], default='video', max_length=6, verbose_name='Wynik')),
                ('resolution', models.CharField(choices=[('1280x720', 'HD 1280×720'), ('1920x1080', 'Full HD 1920×1080'), ('640x360', 'Podgląd 640×360')], default='1280x720', max_length=10, verbose_name='Rozdzielczość')),
                ('seconds', models.PositiveSmallIntegerField(default=12, verbose_name='Długość [s]')),
                ('scene_query', models.CharField(blank=True, default='', max_length=500, verbose_name='Parametry sceny (jak w odtwarzaczu 3D)')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Tytuł')),
                ('status', models.CharField(choices=[('queued', 'W kolejce'), ('running', 'Renderuje się'), ('done', 'Gotowe'), ('error', 'Błąd')], db_index=True, default='queued', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('worker', models.CharField(blank=True, default='', max_length=80, verbose_name='Worker')),
                ('claim_token', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('result', models.FileField(blank=True, upload_to='renders/%Y/%m/', verbose_name='Plik wyniku')),
                ('log', models.TextField(blank=True, default='', verbose_name='Log workera')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='render_jobs', to='twin.warehousemodel', verbose_name='Model hali')),
            ],
            options={
                'verbose_name': 'Zlecenie renderu',
                'verbose_name_plural': 'Zlecenia renderu',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
