# Generated by Django 5.2.17 on 2026-10-05 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('twin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('forecast', 'Prognoza wolumenów'), ('segmentation', 'Segmentacja materiałów')], max_length=14, verbose_name='Rodzaj')),
                ('version', models.CharField(max_length=40, verbose_name='Wersja algorytmu')),
                ('params', models.JSONField(default=dict, verbose_name='Parametry')),
                ('metrics', models.JSONField(default=dict, verbose_name='Miary')),
                ('result', models.JSONField(default=dict, verbose_name='Wynik')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_runs', to='twin.warehousetaskbatch', verbose_name='Import zadań')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Przebieg modelu',
                'verbose_name_plural': 'Przebiegi modeli',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
